package com.semesterdomain.semesterprojekt;

import java.io.Serializable;

/**
 * The type Product represents a single product through of the mapshop.
 */
public class Product implements Serializable {

    /**
     * The product id is the id that is generated by the DB.
     */
    private long productId;
    /**
     * The productname is the name of the product which can be search and selected from the DB.
     */
    private String productName;
    /**
     * The manufacturer is the manufacturer.
     */
    private String manufacturer;
    /**
     * The price of the product in Cents.
     */
    private long price;
    /**
     * The posx is the X coordinate of the postion of the product inside of the shop.
     */
    private double posX;
    /**
     * The posy is the y coordinate of the postion of the product inside of the shop.
     */
    private double posY;


    /**
     * Instantiates a new Product with the given name, manufacturer and price.
     *
     * @param name         the name for the product.
     * @param manufacturer the manufacturer of the product.
     * @param price        the price of the product.
     */
    public Product(String name, String manufacturer, long price) {
        this.productName = name;
        this.manufacturer = manufacturer;
        this.price = price;
    }

    /**
     * Instantiates a new dummy Product for the entrance and the cash register.
     *
     * @param posx the posx the X coordinate.
     * @param posy the posy the Y coordinate.
     */
    public Product(int posx, int posy) {
        this.posX = posx;
        this.posY = posy;
        this.productName = "dummy";
        this.manufacturer = "dummyManufacturer";
        this.price = 0;
    }

    /**
     * Gets product id.
     *
     * @return the product id
     */
    public long getProductId() {
        return productId;
    }

    /**
     * Sets product id.
     *
     * @param product_id the product id
     */
    public void setProductId(long product_id) {
        this.productId = product_id;
    }

    /**
     * Gets product name.
     *
     * @return the product name
     */
    public String getProductName() {
        return productName;
    }

    /**
     * Sets product name.
     *
     * @param productName the product name
     */
    public void setProductName(String productName) {
        this.productName = productName;
    }

    /**
     * Gets manufacturer.
     *
     * @return the manufacturer
     */
    public String getManufacturer() {
        return manufacturer;
    }

    /**
     * Sets manufacturer.
     *
     * @param manufacturer the manufacturer
     */
    public void setManufacturer(String manufacturer) {
        this.manufacturer = manufacturer;
    }

    /**
     * Gets price.
     *
     * @return the price
     */
    public long getPrice() {
        return price;
    }

    /**
     * Sets price.
     *
     * @param price the price
     */
    public void setPrice(long price) {
        this.price = price;
    }

    /**
     * Gets x.
     *
     * @return the x
     */
    public double getX() {
        return posX;
    }

    /**
     * Sets pos x.
     *
     * @param posX the pos x
     */
    public void setPosX(double posX) {
        this.posX = posX;
    }

    /**
     * Gets y.
     *
     * @return the y
     */
    public double getY() {
        return posY;
    }

    /**
     * Sets pos y.
     *
     * @param posY the pos y
     */
    public void setPosY(double posY) {
        this.posY = posY;
    }

    /**
     * Returns the products ID as a string.
     *
     * @return the products ID.
     */
    @Override
    public String toString() {
        return String.valueOf(productId);
    }

    /**
     * Gets the distance to the parameter product.
     *
     * @param product the product
     * @return the distance to
     */
    public double getDistanceTo(Product product) {
        double xDistance = Math.abs(getX() - product.getX());
        double yDistance = Math.abs(getY() - product.getY());
        double distance = Math.sqrt((xDistance * xDistance) + (yDistance * yDistance));

        return distance;
    }

}

