package com.semesterdomain.semesterprojekt;

import java.io.Serializable;
import java.util.ArrayList;

/**
 * The type Shopping list represents a from the user created shoppinglist. Object from this class
 * are stored in the DB.
 */
public class ShoppingList implements Serializable {

    /**
     * The List id is the id that is generated by the DB.
     */
    private long listId;
    /**
     * The My products is used to store the added products before they get serialized into the DB.
     */
    private ArrayList<Product> myProducts = new ArrayList<>();
    /**
     * The Sum price is the price of every product on the list added up.
     */
    private int sumPrice;
    /**
     * The Budget is a value set by the user and is used to warm the user if the sumPrice exceeds budget.
     */
    private int budget;
    /**
     * The Name is a value set by the user when he edites the shoppinglist. There is also a default
     * value if user does not edit the default value.
     */
    private String name;
    /**
     * The Fk user is the id of the user (foreign key) who is the owner of the shopping list. Only this user can
     * delete the shoppinglist.
     */
//id of the owner of the shopping list
    private int fkUser;

    /**
     * Instantiates a new Shopping list.
     */
    public ShoppingList() {
        this.fkUser = 1;
        sumPrice = 0;
        myProducts = new ArrayList<>();
        this.budget = 0;
    }

    /**
     * Calculate sum price int.
     *
     * @param products The products for which the sumPrice is calculated.
     * @return the int
     */
    public int calculateSumPrice(ArrayList<Product> products) {
        sumPrice = 0;
        for (Product p : products) {
            this.sumPrice += p.getPrice();
        }
        return this.sumPrice;
    }

    /**
     * Gets my products.
     *
     * @return the my products
     */
    public ArrayList<Product> getMyProducts() {
        return myProducts;
    }

    /**
     * Sets my products.
     *
     * @param myProducts the my products
     */
    public void setMyProducts(ArrayList<Product> myProducts) {
        this.myProducts = myProducts;
    }

    /**
     * Gets sum price.
     *
     * @return the sum price
     */
    public int getSumPrice() {
        return sumPrice;
    }

    /**
     * Gets name.
     *
     * @return the name
     */
    public String getName() {
        return name;
    }

    /**
     * Sets name.
     *
     * @param name the name
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * Gets fk user (foreign key).
     *
     * @return the fk user (foreign key)
     */
    public int getFkUser() {
        return fkUser;
    }

    /**
     * Sets fk user (foreign key).
     *
     * @param fk_user the fk user (foreign key)
     */
    public void setFkUser(int fk_user) {
        this.fkUser = fk_user;
    }

    /**
     * Gets list id.
     *
     * @return the list id
     */
    public long getListId() {
        return listId;
    }

    /**
     * Sets list id.
     *
     * @param list_id the list id
     */
    public void setListId(long list_id) {
        this.listId = list_id;
    }

    /**
     * Gets budget.
     *
     * @return the budget
     */
    public int getBudget() {
        return budget;
    }

    /**
     * Sets budget.
     *
     * @param budget the budget
     */
    public void setBudget(int budget) {
        this.budget = budget;
    }

}
