package com.semesterdomain.semesterprojekt;

import java.io.Serializable;
import java.util.ArrayList;

/**
 * The type Shopping list represents a from the user created shoppinglist. Object from this class
 * are stored in the DB.
 */
public class ShoppingList implements Serializable {

    /**
     * The List id is the id that is generated by the DB.
     */
    private long listId;
    /**
     * The My products is used to store the added products before they get serialized into the DB.
     */
    private ArrayList<Product> myProducts = new ArrayList<>();
    /**
     * The Sum price is the price of every product on the list added up.
     */
    private int sumPrice;
    /**
     * The Budget is a value set by the user and is used to warn the user if the sumPrice exceeds budget.
     */
    private int budget;
    /**
     * The Name is the shoppinglist name set by the user when he edits a shoppinglist. This Field
     * also got a default value until the user edits the name for the first time.
     */
    private String name;
    /**
     * The Fk user is the ID of the user (foreign key) who is the owner of the shopping list.
     * Only this user can delete the his shoppinglists.
     */
//id of the owner of the shopping list
    private int fkUser;

    /**
     * Instantiates a new shoppinglist.
     */
    public ShoppingList() {
        this.fkUser = 1;
        sumPrice = 0;
        myProducts = new ArrayList<>();
        this.budget = 0;
    }

    /**
     * Calculate sumPrice for the whole shoppinglist.
     *
     * @return the int value of the sumPrice.
     */
    public int calculateSumPrice() {
        sumPrice = 0;
        for (Product p : myProducts) {
            this.sumPrice += (p.getPrice() * p.getAmount());
        }
        return this.sumPrice;
    }

    /**
     * Gets my products.
     *
     * @return the my products
     */
    public ArrayList<Product> getMyProducts() {
        return myProducts;
    }

    /**
     * Sets my products.
     *
     * @param myProducts the my products.
     */
    public void setMyProducts(ArrayList<Product> myProducts) {
        this.myProducts = myProducts;
    }

    /**
     * Gets sumPrice.
     *
     * @return the sumPrice.
     */
    public int getSumPrice() {
        return sumPrice;
    }

    /**
     * Gets name.
     *
     * @return the name.
     */
    public String getName() {
        return name;
    }

    /**
     * Sets name.
     *
     * @param name the name.
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * Gets fk user (foreign key).
     *
     * @return the fk user (foreign key).
     */
    public int getFkUser() {
        return fkUser;
    }

    /**
     * Sets fk user (foreign key).
     *
     * @param fkUser the fk user (foreign key).
     */
    public void setFkUser(int fkUser) {
        this.fkUser = fkUser;
    }

    /**
     * Gets id of the shoppinglist.
     *
     * @return the shoppinglist id
     */
    public long getListId() {
        return listId;
    }

    /**
     * Sets id of the shoppinglist.
     *
     * @param listId the shoppinglist id
     */
    public void setListId(long listId) {
        this.listId = listId;
    }

    /**
     * Gets the budget for a shoppinglist.
     *
     * @return the budget.
     */
    public int getBudget() {
        return budget;
    }

    /**
     * Sets the budget for a shoppinglist.
     *
     * @param budget the budget
     */
    public void setBudget(int budget) {
        this.budget = budget;
    }

}
