DROP TABLE IF EXISTS "LIST";
CREATE TABLE "LIST" 
(
	"list_id" INTEGER PRIMARY KEY  AUTOINCREMENT  NOT NULL  UNIQUE ,
	"listname" TEXT NOT NULL  DEFAULT Einkaufsliste ,
	"fk_user" INTEGER, 
	FOREIGN KEY(fk_user) REFERENCES USER(user_id),
	CHECK(
		typeof("listname") = "text" AND
		length("listname") <= 100
	)
);
INSERT INTO "LIST" VALUES(1,'Shopping List',1);
DROP TABLE IF EXISTS "LIST_PRODUCT";
CREATE TABLE "LIST_PRODUCT" 
(
	"list_product_id" INTEGER PRIMARY KEY  AUTOINCREMENT  NOT NULL  UNIQUE ,
	"fk_list" INTEGER NOT NULL ,
	"fk_product" INTEGER NOT NULL,
	FOREIGN KEY(fk_list) REFERENCES LIST(list_id),
	FOREIGN KEY(fk_product) REFERENCES PRODUCT(product_id)
);
INSERT INTO "LIST_PRODUCT" VALUES(1,1,1);
DROP TABLE IF EXISTS "LIST_PSEUDO";
CREATE TABLE "LIST_PSEUDO" 
(
	"list_pseudo_id" INTEGER PRIMARY KEY  AUTOINCREMENT  NOT NULL  UNIQUE ,
	"fk_list" INTEGER NOT NULL ,
	"fk_pseudo" INTEGER NOT NULL,
	FOREIGN KEY(fk_list) REFERENCES LIST(list_id),
	FOREIGN KEY(fk_pseudo) REFERENCES PSEUDO(pseudo_id)
);
DROP TABLE IF EXISTS "PRODUCT";
CREATE TABLE "PRODUCT" 
(
	"product_id" INTEGER PRIMARY KEY  AUTOINCREMENT  NOT NULL  UNIQUE ,
	"productname" TEXT NOT NULL ,
	"manufacturer" TEXT NOT NULL ,
	"productprice" INTEGER NOT NULL ,
	"posx" REAL NOT NULL ,
	"posy" REAL NOT NULL 
);
INSERT INTO "PRODUCT" VALUES(1,'Testproduct','Testmanufacturer',10,1,1);
INSERT INTO "PRODUCT" VALUES(2,'Testproduct','Testmanufacturer',10,1,1);
DROP TABLE IF EXISTS "PSEUDO";
CREATE TABLE "PSEUDO" 
(
	"pseudo_id" INTEGER PRIMARY KEY  AUTOINCREMENT  NOT NULL  UNIQUE ,
	"pseudoname" TEXT NOT NULL  UNIQUE 
);
INSERT INTO "PSEUDO" VALUES(1,'Testpseudo');
DROP TABLE IF EXISTS "PSEUDO_PRODUCT";
CREATE TABLE "PSEUDO_PRODUCT" 
(
	"pseudo_product_id" INTEGER PRIMARY KEY  AUTOINCREMENT  NOT NULL  UNIQUE ,
	"fk_product" INTEGER NOT NULL ,
	"fk_pseudo" INTEGER NOT NULL,
	FOREIGN KEY(fk_product) REFERENCES PRODUCT(product_id),
	FOREIGN KEY(fk_pseudo) REFERENCES PSEUDO(pseudo_id)
);
INSERT INTO "PSEUDO_PRODUCT" VALUES(1,1,1);
DROP TABLE IF EXISTS "RIGHT";
CREATE TABLE "RIGHT"
(
	"right_id" INTEGER PRIMARY KEY  AUTOINCREMENT  NOT NULL  UNIQUE ,
 	"fk_list" INTEGER NOT NULL , 
	"fk_user" INTEGER,
	FOREIGN KEY(fk_list) REFERENCES LIST(list_id),
	FOREIGN KEY(fk_user) REFERENCES USER(user_id)
);
INSERT INTO "RIGHT" VALUES(1,1,1);
DROP TABLE IF EXISTS "USER";
CREATE TABLE "USER" 
(
	"user_id" INTEGER PRIMARY KEY  AUTOINCREMENT  NOT NULL  UNIQUE , 
	"username" TEXT,
	CHECK(
		typeof("username") = "text" AND
		length("username") <= 100
	)
);
INSERT INTO "USER" VALUES(1,'Testuser');
INSERT INTO "USER" VALUES(2,'Testuser1');
INSERT INTO "USER" VALUES(3,'Testuser1');
INSERT INTO "USER" VALUES(4,'Testuser');
INSERT INTO "USER" VALUES(5,'Testuser');
