package com.semesterdomain.semesterprojekt;

import java.io.Serializable;

/**
 * The type User is the user for the Application. Object from this class are stored in the DB.
 */
public class User implements Serializable {

    /**
     * The User id is the id that is generated by the DB.
     */
    private int userId;
    /**
     * The Username is the name of the user and in this version this attribute is hardcoded.
     */
    private String username;

    /**
     * Instantiates a new User.
     *
     * @param username the username
     */
    public User(String username) {
        this.username = username;
        this.userId = 1;
    }

    /**
     * Gets username.
     *
     * @return the username
     */
    public String getUsername() {
        return username;
    }

    /**
     * Sets username.
     *
     * @param username the username
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * Gets user id.
     *
     * @return the user id
     */
    public int getUserId() {
        return userId;
    }

    /**
     * Sets user id.
     *
     * @param userId the user id
     */
    public void setUserId(int userId) {
        this.userId = userId;
    }
}
